### ISSUE TITLE
Creating a database "nadeef" and an error 

### ISSUE THREAD

**Issue by vishvapalsinh** [BigDaMa/abstraction-layer#11]
Dear Contributors, 

I am currently running this tool.
I implemented it on a Windows machine by following the installation guidelines. 

1. Creating nadeef database:
Should I only create a database called the "nadeef" or add the relational schema?
If it needs schema then from where can I find it?

2. Error message:
I am getting an error. 
It is looking for the attribute in the 
I wanted to know whether it is generated automatically while running a code or if one should create it manually.

```
cursor.execute("""SELECT * from violation WHERE tablename = '{}';""".format(table_name))
psycopg2.errors.UndefinedTable: FEHLER:  Relation »violation« existiert nicht
LINE 1: SELECT * from violation WHERE tablename = 'TB_TOY_19VVH4KC23...
```

Thank you 

Note: It would be nice to have a "discussion" section for this repository such that one can have general as well as specific discussions.

**Comment by m-mahdavi** [comment]
Thanks for your feedback and interest. This project is not actively being maintained anymore. We have not tested it on Windows. On Linux/Ubuntu, you need to create a database named nadeef. This is the requirement of one of the third-party tools (i.e., NADEEF), which we are trying to cover in this project. NADEEF stores its results in this database. I suggest looking at the documentations of NADEEF.

**Comment by vishvapalsinh** [comment]
Thank you for your response. I really appreciate it. 
Now, I will look for ways to run it successfully on Linux/Ubuntu.
