### ISSUE TITLE
Clean up postgres tables created by NADEEF

### ISSUE THREAD

**Issue by FelixNeutatz** [BigDaMa/abstraction-layer#4]
As far as I can follow the code, the tables that have been created by NADEEF are not cleaned up after a run.
We should add:
cursor.execute("DROP TABLE tb_" + name + ";")
cursor.execute("TRUNCATE violation;")
cursor.execute("TRUNCATE repair;")
cursor.execute("TRUNCATE audit;")

**Comment by m-mahdavi** [comment]
Yes. That is also neglected. Thanks.

**Comment by m-mahdavi** [comment]
Already done.
