### ISSUE TITLE
Parameterize method install_tools()

### ISSUE THREAD

**Issue by FelixNeutatz** [BigDaMa/abstraction-layer#5]
It would be great if we would be able to pass e.g. Postgres user and password as optional parameters of the method install_tools(). If the parameters are specified, we can still ask the user to enter them using raw_input().

**Comment by m-mahdavi** [comment]
I am curious about the use case of this feature. For example, do you need to call install_tools() from another program? By the way, OK we also consider that.

**Comment by FelixNeutatz** [comment]
The use case is that I want to run the cleaning API methods in my project :)

**Comment by m-mahdavi** [comment]
I know. And that is why we try to keep the API functions simple and logical. 
But, install_tools() method is not a function that you call it every day. :) You need to call it only "once" to install and configure tools on your system. 
By the way, if you still think for that particular one time, you need to call the function in your project, we will add the arguments to the method. :)

**Comment by m-mahdavi** [comment]
For now, this method is excluded from the project.
