### ISSUE TITLE
Feature Request: Make it possible to run several datasets in parallel

### ISSUE THREAD

**Issue by FelixNeutatz** [BigDaMa/abstraction-layer#9]
See my approach to make parallelization possible for KATARA:
https://github.com/FelixNeutatz/abstraction-layer/commit/70e9ce799c2ea2f9a3d1b81ceccdc1a802833bfc

**Comment by m-mahdavi** [comment]
Now, all the tools support parallelization except NADEEF. For NADEEF there is a danger of loosing data and getting exceptions. So, for now, it is not still parallelized.

**Comment by m-mahdavi** [comment]
OK, all the tools including NADEEF can be run in parallel.
